name: Run Test And Build
on:
  push:
    branches:
      - dev

  workflow_dispatch:
    branches:
      - dev
      - "feat/**"

jobs:
  # 1. 테스트 job
  test:
    runs-on: ubuntu-latest
    steps:
      # 코드를 가져옴
      - name: Get Codes
        uses: actions/checkout@v4

      # 의존성 파일들 설치
      - name: Install Dependencies
        run: npm install

      # 테스트 실행
      - name: Run Test
        run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build
